---
overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params: [ "quiet" ]
defaults:
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: "0"
    GRUB_DISABLE_OS_PROBER: true
always_use_defaults: false
