# HERMETISMO: sin comprobación de internet, sin geoip, sin enlaces externos.
---
showSupportUrl:         false
showKnownIssuesUrl:     false
showReleaseNotesUrl:    false
requirements:
    requiredStorage:    8.0
    requiredRam:        1.0
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root
geoip:
    style:    "none"
